### ISSUE TITLE
Mod compatibility: Spells added by CtB are using fixed SPWI/SPPR indices instead of ADD_SPELL.

### ISSUE THREAD

**Issue by GraionDilach** [SpellholdStudios/Check_the_Bodies#29]
Considering that most mods these days filter using ADD_SPELL and SPELL.IDS, this can affect megamod runs in various ways, either via overwriting other mod-added spells/introducing duplicates/breaking assumptions via overwriting more popular variants from SR or IWD.

The best option would be to convert the spells to ADD_SPELL and (maybe) only install them individually if they're missing from the game (the scrolls could always install at worst as a duplicate of an existing scroll afterall), akin to the solution DSotSC-Trilogy migrated to.

**Comment by weigo87** [comment]
> The best option would be to convert the spells to ADD_SPELL and (maybe) only install them individually if they're missing from the game (the scrolls could always install at worst as a duplicate of an existing scroll afterall), akin to the solution DSotSC-Trilogy migrated to.

The new pull request contains the change with the spells. The number of spell.ids entries has been reduced to a minimum and all learnable spells are installed with the ADD_SPELL command.

**Comment by GraionDilach** [comment]
Thank you!
